from __future__ import annotations

import json
import os
import urllib.error
import urllib.request

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse

app = FastAPI(title="AI Music Video Studio Control", version="0.13.0")


def _worker_url() -> str:
    return os.getenv("RENDER_WORKER_URL", "").strip().rstrip("/")


def _worker_json(path: str, timeout: float = 4.0) -> dict:
    base = _worker_url()
    if not base:
        raise RuntimeError("RENDER_WORKER_URL no configurado")
    req = urllib.request.Request(f"{base}/{path.lstrip('/')}", headers={"User-Agent": "AI-Music-Video-Studio-Vercel/0.13.0"})
    with urllib.request.urlopen(req, timeout=timeout) as response:
        payload = json.loads(response.read().decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Respuesta inválida del worker")
    return payload


def _worker_health() -> dict:
    base = _worker_url()
    if not base:
        return {"configured": False, "online": False, "worker_url": None}
    try:
        return {"configured": True, "online": True, "worker_url": base, "worker": _worker_json("/api/health", 3.0)}
    except Exception as exc:
        return {"configured": True, "online": False, "worker_url": base, "error": str(exc)}


@app.get("/api/control/health")
def control_health():
    return {"ok": True, "version": app.version, **_worker_health()}


@app.get("/api/control/checkpoints")
def control_checkpoints():
    try:
        return JSONResponse({"worker_configured": True, **_worker_json("/api/comfyui/checkpoints", 5.0)})
    except Exception as exc:
        return JSONResponse({"worker_configured": bool(_worker_url()), "online": False, "count": 0, "checkpoints": [], "error": str(exc)})


@app.get("/api/control/config")
def control_config():
    base = _worker_url()
    return {"worker_configured": bool(base), "worker_url": base or None, "version": app.version}


PAGE = r'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Music Video Studio</title><style>
*{box-sizing:border-box}body{margin:0;background:#080a10;color:#f7f7fb;font-family:Inter,system-ui,sans-serif}.shell{max-width:1240px;margin:auto;padding:36px 20px 70px}h1{font-size:clamp(42px,6vw,72px);letter-spacing:-.055em;margin:8px 0 14px}.eyebrow{font-size:12px;letter-spacing:.16em;color:#929ab4;font-weight:800}.hero p{max-width:850px;color:#abb3c7;font-size:17px}.badge{display:inline-block;border:1px solid #30364a;background:#111522;border-radius:999px;padding:7px 10px;margin:6px 6px 0 0;font-size:12px}.notice,.card,.local,.progress,.flow{border:1px solid #292f40;background:#10141e;border-radius:18px;padding:16px}.notice{margin:26px 0 18px}.connect{display:grid;grid-template-columns:1fr auto auto;gap:8px;margin-top:10px}.layout{display:grid;grid-template-columns:.9fr 1.1fr;gap:20px}.card{padding:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.full{grid-column:1/-1}label{display:block;font-size:12px;font-weight:800;margin-bottom:6px}input,select,textarea{width:100%;border:1px solid #343a4d;background:#090c13;color:white;border-radius:11px;padding:12px;font:inherit}textarea{min-height:95px}button{border:0;border-radius:11px;padding:11px 13px;background:#292f42;color:white;font-weight:800;cursor:pointer}button:disabled{opacity:.42;cursor:not-allowed}.primary{width:100%;padding:14px;background:linear-gradient(135deg,#7258ff,#d84fc7)}.auto{background:linear-gradient(135deg,#6f58ff,#b449d2)}.final{background:#17684f}.danger{background:#5b242d}.local{margin-bottom:13px;background:#111020}.path,.hint{font-size:11px;color:#929aaf;margin-top:7px;word-break:break-all}.row{display:flex;gap:8px;align-items:center;justify-content:space-between}.progress{margin-top:13px}.phead{display:flex;justify-content:space-between;font-size:12px}.track{height:10px;background:#202537;border-radius:999px;margin-top:9px;overflow:hidden}.fill{height:100%;width:0;background:linear-gradient(90deg,#7258ff,#d84fc7);transition:.3s}.status{white-space:pre-wrap;margin-top:12px;background:#090c13;border:1px solid #292f40;border-radius:12px;padding:12px;color:#cbd0df;min-height:55px}.story{display:grid;gap:9px;max-height:680px;overflow:auto}.scene{border:1px solid #292f40;border-radius:12px;padding:12px;background:#090c13}.scene p{font-size:12px;color:#929aaf}.meta{font-size:11px;color:#a38fff}.flow{margin-top:13px}.steps{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.step{font-size:11px;border:1px solid #30364a;border-radius:999px;padding:6px 8px;color:#8f98af}.step.on{color:white;border-color:#7258ff}.step.done{color:#9fe0c6;border-color:#245c49}.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.actions .final{grid-column:1/-1}.preview video{width:100%;margin-top:12px;border-radius:12px}@media(max-width:900px){.layout,.grid,.connect,.actions{grid-template-columns:1fr}.full,.actions .final{grid-column:auto}}
</style></head><body><main class="shell"><section class="hero"><div class="eyebrow">VERCEL CONTROL PLANE · ARCHIVOS LOCALES</div><h1>AI Music Video Studio</h1><p>Vercel manda órdenes; la canción y la foto/video se leen directamente desde una carpeta de tu Mac. Los archivos pesados no viajan por Cloudflare.</p><span class="badge">Vercel</span><span class="badge">ComfyUI</span><span class="badge">Local media</span><span id="badge" class="badge">Worker: desconectado</span></section>
<div class="notice"><b>Worker</b><div class="connect"><input id="wu" placeholder="https://xxxxx.trycloudflare.com"><button id="connect">Conectar</button><button id="disconnect" class="danger">Desconectar</button></div><div id="conn" class="hint">El túnel se usa solo para órdenes y estados.</div></div>
<div class="layout"><section class="card"><h2>Nuevo videoclip</h2><div class="local"><div class="row"><b>Carpeta local de entrada</b><button id="refreshIn" disabled>Actualizar archivos</button></div><div id="path" class="path">Conectá el worker.</div></div><div class="grid"><div><label>Canción local</label><select id="song" disabled></select></div><div><label>Foto o video local</label><select id="visual" disabled></select></div><div><label>Título</label><input id="title" placeholder="Mi videoclip"></div><div><label>Estilo</label><select id="style"><option value="cinematic rock">Cinematic Rock</option><option value="romantic film">Romántico</option><option value="urban night">Urbano nocturno</option><option value="live performance">Performance</option><option value="dreamlike surreal">Surreal / Dream</option></select></div><div><label>Formato</label><select id="aspect"><option>16:9</option><option>9:16</option></select></div><div><label>Calidad</label><select id="quality"><option value="preview">Preview</option><option value="final">Final 1080p</option><option value="master">Master</option></select></div><div class="full"><label>Letra (opcional)</label><textarea id="lyrics"></textarea></div><div class="full"><label>Checkpoint ComfyUI</label><div class="row"><select id="cp" disabled></select><button id="refreshCp" disabled>Actualizar</button></div><div id="cpHint" class="hint"></div></div><div class="full"><button id="create" class="primary" disabled>Crear storyboard con archivos locales</button></div></div><div class="progress"><div class="phead"><b id="stage">En espera</b><span id="pmeta">0% · 00:00</span></div><div class="track"><div id="fill" class="fill"></div></div><div id="detail" class="hint">Los medios permanecen en tu Mac.</div></div><div id="status" class="status">Conectá el worker.</div><div id="preview" class="preview"></div></section>
<section class="card"><h2>Storyboard</h2><div id="story" class="story"><p class="hint">Creá un proyecto para ver las escenas.</p></div><div class="flow"><div class="steps"><span id="st1" class="step on">1 · Storyboard</span><span id="st2" class="step">2 · Generar escenas</span><span id="st3" class="step">3 · Revisar / aprobar</span><span id="st4" class="step">4 · Videoclip final</span></div><div class="actions"><button id="approveSb" disabled>✅ Aprobar storyboard</button><button id="genAll" class="auto" disabled>🎬 Generar todas las escenas</button><button id="final" class="final" disabled>🎞 Generar videoclip final</button></div><div id="flowState" class="hint">Creá un proyecto para comenzar.</div></div></section></div></main><script>
const SERVER_WORKER=__SERVER_WORKER__,$=q=>document.querySelector(q);let W='',project=null,rows=[],sbApproved=false,busy=false,start=0,timer=null,pct=0;const running=new Set();const wu=$('#wu'),badge=$('#badge'),conn=$('#conn'),song=$('#song'),visual=$('#visual'),pathEl=$('#path'),cp=$('#cp'),create=$('#create'),status=$('#status'),story=$('#story'),preview=$('#preview'),stage=$('#stage'),pmeta=$('#pmeta'),fill=$('#fill'),detail=$('#detail'),approveSb=$('#approveSb'),genAll=$('#genAll'),finalBtn=$('#final'),flowState=$('#flowState'),steps=[1,2,3,4].map(i=>$('#st'+i));
function norm(v){v=String(v||'').trim();if(!v)return'';if(!/^https?:\/\//i.test(v))v='https://'+v;return v.replace(/\/+$/,'')}function url(p){return W+p}function esc(x){const d=document.createElement('div');d.textContent=String(x??'');return d.innerHTML}function elapsed(){if(!start)return'00:00';const s=Math.floor((Date.now()-start)/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function drawP(){fill.style.width=Math.min(100,pct)+'%';pmeta.textContent=Math.round(pct)+'% · '+elapsed()}function begin(a,b,p=0){start=Date.now();pct=p;stage.textContent=a;detail.textContent=b;clearInterval(timer);timer=setInterval(drawP,500);drawP()}function progress(p,a,b=''){pct=Math.max(pct,p);stage.textContent=a;if(b)detail.textContent=b;drawP()}function done(a,b=''){pct=100;stage.textContent=a;detail.textContent=b;drawP();clearInterval(timer)}function fail(e){stage.textContent='Error';detail.textContent=e;clearInterval(timer);drawP()}
function step(n){steps.forEach((e,i)=>{e.classList.toggle('done',i+1<n);e.classList.toggle('on',i+1===n)})}function flow(){approveSb.disabled=!project||sbApproved||busy;const ready=rows.length&&rows.every(x=>x.status==='ready_for_review'||x.auto_pipeline_state==='ready_for_review'),approved=rows.length&&rows.every(x=>x.approved);genAll.disabled=!project||!sbApproved||busy||!cp.value;finalBtn.disabled=!approved||busy;if(!project){step(1);flowState.textContent='Creá un proyecto para comenzar.'}else if(!sbApproved){step(1);flowState.textContent='Revisá y aprobá el storyboard.'}else if(!ready){step(2);flowState.textContent='Generá todas las escenas.'}else if(!approved){step(3);flowState.textContent='Revisá y aprobá cada escena.'}else{step(4);flowState.textContent='Listo para generar el videoclip final.'}}
function opts(el,list,msg){el.innerHTML=list.length?list.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} · ${x.size_mb} MB</option>`).join(''):`<option value="">${msg}</option>`;el.disabled=!list.length}async function inputs(){try{const r=await fetch(url('/api/local-inputs'),{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.detail||'No disponible');pathEl.textContent=j.input_dir;opts(song,j.audio||[],'Sin audio');opts(visual,j.visuals||[],'Sin imagen/video');create.disabled=!(j.audio_count&&j.visual_count);status.textContent=`Locales: ${j.audio_count} audio · ${j.visual_count} visuales`}catch(e){pathEl.textContent='Actualizá y reiniciá el worker para habilitar modo local.';create.disabled=true;status.textContent='Modo local: '+e.message}}
async function models(){try{const r=await fetch(url('/api/comfyui/checkpoints'),{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.detail||j.error);const m=j.checkpoints||[];cp.innerHTML=m.length?m.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''):'<option value="">Sin modelos</option>';cp.disabled=!m.length;$('#cpHint').textContent=`${m.length} modelo(s) detectado(s)`;flow()}catch(e){cp.disabled=true;$('#cpHint').textContent=e.message}}
async function connect(silent=false){const c=norm(wu.value||localStorage.getItem('renderWorkerUrl')||SERVER_WORKER);if(!c)return;wu.value=c;try{badge.textContent='Worker: conectando…';const r=await fetch(c+'/api/health',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error('offline');W=c;localStorage.setItem('renderWorkerUrl',c);badge.textContent='Worker: online';conn.textContent=`${c} · worker ${j.version||'n/d'}`;$('#refreshIn').disabled=false;$('#refreshCp').disabled=false;await Promise.all([inputs(),models()])}catch(e){W='';badge.textContent='Worker: offline';if(!silent)status.textContent='No se pudo conectar'}}
$('#connect').onclick=()=>connect(false);$('#disconnect').onclick=()=>{W='';localStorage.removeItem('renderWorkerUrl');badge.textContent='Worker: desconectado';create.disabled=true};$('#refreshIn').onclick=inputs;$('#refreshCp').onclick=models;cp.onchange=flow;
create.onclick=async()=>{if(!W||!song.value||!visual.value)return;begin('Creando storyboard','Leyendo archivos directamente desde la Mac…',5);create.disabled=true;try{const r=await fetch(url('/api/projects/from-local'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({song_name:song.value,visual_name:visual.value,title:$('#title').value,style:$('#style').value,aspect:$('#aspect').value,quality:$('#quality').value,lyrics:$('#lyrics').value})}),j=await r.json();if(!r.ok)throw Error(j.detail||'Error');project=j.id;rows=j.storyboard||[];sbApproved=false;done('Storyboard listo',`${rows.length} escenas`);status.textContent=`Proyecto ${j.id}\nDuración ${Number(j.duration||0).toFixed(1)}s · BPM ${j.analysis?.bpm??'n/d'}\n${rows.length} escenas · archivos locales`;draw(rows);flow()}catch(e){fail(e.message);status.textContent='Error: '+e.message}finally{create.disabled=false}};
function draw(r){rows=r||[];story.innerHTML=rows.map(x=>{const ready=x.status==='ready_for_review'||x.auto_pipeline_state==='ready_for_review';return `<div class="scene"><div><b>ESCENA ${x.id} · ${x.start}s–${x.end}s</b> <span class="meta">${x.status||'planned'}</span></div><p>${esc(x.lyrics||x.director_prompt||x.prompt)}</p><button class="auto" onclick="one(${x.id})" ${busy?'disabled':''}>✨ Generar / regenerar</button><button class="${x.approved?'final':''}" onclick="approve(${x.id},${!x.approved})" ${ready?'':'disabled'}>${x.approved?'Aprobada ✓':'Aprobar escena'}</button></div>`}).join('');flow()}async function reload(){const r=await fetch(url(`/api/projects/${project}`)),j=await r.json();if(!r.ok)throw Error(j.detail||'Proyecto');draw(j.storyboard||[]);return j}function state(j){const l=(j.log||[]).slice(-1)[0]||{},s=j.auto_state||'';if(s==='ready_for_review')return[100,'Lista para revisar'];if(s==='waiting_video'||l.stage==='video')return[50,'Generando video'];if(s==='waiting_image'||l.stage==='image')return[25,'Generando imagen'];if(l.stage==='face_refine')return[65,'Identidad'];if(l.stage==='lipsync')return[78,'Lip-sync'];if(l.stage==='upscale')return[90,'Upscale'];return[10,'Preparando']}
async function run(id,cb){for(let i=0;i<900;i++){const r=await fetch(url(`/api/projects/${project}/scenes/${id}/auto-pipeline`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({checkpoint:cp.value,fps:24,use_face_refine:true,use_lipsync:true,use_upscale:true,strict_optional:false})}),j=await r.json();if(!r.ok)throw Error(j.detail||JSON.stringify(j));const [p,n]=state(j),l=(j.log||[]).slice(-1)[0];cb&&cb(p,n,l,j);await reload();if(j.auto_state==='ready_for_review')return j;if(j.auto_state==='failed'||j.auto_state==='blocked')throw Error(j.last_error||j.auto_state);await new Promise(x=>setTimeout(x,(j.auto_state==='waiting_image'||j.auto_state==='waiting_video')?2500:500))}throw Error('Tiempo agotado')}
async function one(id){if(running.has(id)||busy)return;running.add(id);begin(`Escena ${id}`,'Procesando…',2);try{await run(id,(p,n,l)=>progress(p,n,l?.detail||l?.status||''));done('Escena lista','Revisala y aprobala')}catch(e){fail(e.message);status.textContent=e.message}finally{running.delete(id)}}
approveSb.onclick=()=>{sbApproved=true;status.textContent=`Storyboard aprobado ✓\n${rows.length} escenas`;flow()};genAll.onclick=async()=>{if(!project||busy)return;busy=true;draw(rows);begin('Generando escenas',`0/${rows.length}`,1);try{for(let i=0;i<rows.length;i++){const id=rows[i].id;await run(id,(p,n,l)=>progress(((i+p/100)/rows.length)*100,`Escena ${i+1}/${rows.length} · ${n}`,l?.detail||l?.status||''));progress(((i+1)/rows.length)*100,`Escena ${i+1}/${rows.length} lista`)}done('Todas las escenas generadas','Revisá y aprobá');status.textContent='Escenas generadas ✓'}catch(e){fail(e.message);status.textContent='Generación detenida: '+e.message}finally{busy=false;draw(rows)}};async function approve(id,v){const r=await fetch(url(`/api/projects/${project}/scenes/${id}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:v})}),j=await r.json();if(!r.ok){status.textContent=j.detail||'Error';return}await reload();status.textContent=`Escena ${id}: ${v?'aprobada ✓':'sin aprobar'}`}
finalBtn.onclick=async()=>{begin('Armando videoclip final','Uniendo escenas con la canción original…',5);try{const r=await fetch(url(`/api/projects/${project}/assemble-ai`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved_only:true})}),j=await r.json();if(!r.ok)throw Error(j.detail||'Error');done('Videoclip terminado','Listo para descargar');const u=url(j.download_url||`/api/projects/${project}/download-ai`);preview.innerHTML=`<video controls src="${u}"></video><p><a href="${u}" target="_blank">⬇ Descargar MP4</a></p>`;status.textContent='Videoclip final listo ✓'}catch(e){fail(e.message);status.textContent=e.message}};
wu.value=localStorage.getItem('renderWorkerUrl')||SERVER_WORKER||'';if(wu.value)connect(true);
</script></body></html>'''


@app.get("/", response_class=HTMLResponse)
def home() -> str:
    return PAGE.replace("__SERVER_WORKER__", json.dumps(_worker_url()))
